<?php
return [
    'active' => true,
    'type' => 'cpt',
    'name' => 'service',
    'supports' => [
        'title',
        'editor',
        'comments',
        'revisions',
        'excerpt',
        'page-attributes',
        'thumbnail',
    ],
    'labels' => [
        'has_one' => 'Service',
        'has_many' => 'Services',
        'text_domain' => 'sage',
        'overrides' => [
            'name' => 'Services',
            'singular_name' => 'Service',
            'menu_name' => 'Services',
            'name_admin_bar' => 'Service',
            'add_new' => 'Add New',
            'add_new_item' => 'Add New Service',
            'edit_item' => 'Edit Service',
            'new_item' => 'New Service',
            'view_item' => 'View Service',
            'view_items' => 'View Services',
            'search_items' => 'Search Services',
            'not_found' => 'No books found.',
            'not_found_in_trash' => 'No books found in Trash.',
            'parent_item-colon' => 'Parent Services:',
            'all_items' => 'All Services',
            'archives' => 'Service Archives',
            'attributes' => 'Service Attributes',
            'insert_into_item' => 'Insert into book',
            'uploaded_to_this_item' => 'Uploaded to this book',
            'featured_image' => 'Featured Image',
            'set_featured_image' => 'Set featured image',
            'remove_featured_image' => 'Remove featured image',
            'use_featured_image' => 'Use featured image',
            'filter_items_list' => 'Filter books list',
            'items_list_navigation' => 'Services list navigation',
            'items_list' => 'Services list',
        ],
    ],
    'config' => [
        'public' => true,
        'publicly_queryable' => true,
        'menu_icon' => 'dashicons-rest-api',
        'show_ui' => true,
        'show_in_menu' => true,
        'query_var' => 'service',
        'has_archive' => true,
        'hierarchical' => true,
        'menu_position' => null,
        'can_export' => true,
        'show_in_rest' => true,
        'rest_base' => 'service',
        'capability_type' => 'service',
        'map_meta_cap' => true,
        'taxonomies' => [
            'sector'
        ],
        'rewrite' => [
            'slug' => 'service',
            'with_front' => true,
            'feeds' => true,
            'pages' => true,
        ],
    ],
];
