<?php
return [
    'active' => true,
    'type' => 'cat',
    'name' => 'sector',
    'links' => [
        'service',
    ],
    'labels' => [
        'has_one' => 'Sector',
        'has_many' => 'Sectors',
        'text_domain' => 'sage',
        'overrides' => [
            'name' => 'Sectors',
            'singular_name' => 'Sector',
            'search_items' => 'Search Sectors',
            'popular_items' => 'Popular Sectors',
            'all_items' => 'All Sectors',
            'parent_item' => 'Parent Sector',
            'parent_item_colon' => 'Parent Sector:',
            'edit_item' => 'Edit Sector',
            'view_item' => 'View Sector',
            'update_item' => 'Update Sector',
            'add_new_item' => 'Add New Sector',
            'new_item_name' => 'New Sector Name',
            'separate_items_with_commas' => 'Separate sectors with commass',
            'add_or_remove_items' => 'Add or remove sectors',
            'choose_from_most_used' => 'Choose from the most used sectors',
            'not_found' => 'No sectors found.',
            'no_terms' => 'No sectors',
            'items_list_navigation' => 'Sectors list navigation',
            'items_list' => 'Sectors list',
        ],
    ],
    'config' => [
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'rest_base' => 'sector',
        'rest_controller_class' => 'WP_REST_Terms_Controller',
        'show_tagcloud' => true,
        'show_in_quick_edit' => true,
        'show_admin_column' => false,
        'capabilities' => [
            'manage_terms' => 'manage_categories',
            'edit_terms' => 'manage_categories',
            'delete_terms' => 'manage_categories',
            'assign_terms' => 'edit_posts',
        ],
        'rewrite' => [
            'slug' => 'sector',
            'hierarchical' => true,
        ],
    ],
];
